name: flutter_getx_architecture
description: Flutter GetX Architecture Demo Application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  uuid: ^4.2.1
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.11.1
  excel: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/db_seed/
